package saboteur

import (
	"errors"
	"fmt"
	"sort"

	"github.com/WrdCstlg/pro-thesis/internal/perturber"
	"github.com/WrdCstlg/pro-thesis/internal/recorder"
	"github.com/WrdCstlg/pro-thesis/pkg/schema"
)

// ---------------------------------------------------------------------------
// A.5's adversarial tree
//
// Every node is a COMPLETE fault schedule: the root's committed prefix plus one
// ladder action per edge down to it. A rollout executes that schedule as a real
// world, which is why the tree is tiny and why the ordering of children matters
// far more than the arithmetic that scores them.
//
// # The honest statement of what this tree does (D-015, OQ-013)
//
// The exploration term is +Inf at zero visits, so an unvisited child always
// wins. At Addendum A's budgets no node is ever visited twice, U_avg is never
// read, backpropagation never changes a decision and A.5's pruning rule
// ("visited >= 3 times") is unreachable. In that regime this tree IS
// ladder-ordered enumeration with the expansion order below as its prior.
//
// So the expansion order is where the search actually lives, and Stats()
// reports (as a measured count, not a claim) how many selections were
// INFORMED (every child visited, so the scores decided) versus FORCED (an
// unvisited child existed, so the order decided). A run reporting zero informed
// selections is a run in which the tree contributed nothing measurable. That is
// a finding to publish, not a defect to paper over.
//
// # The expansion order, and why each tier is in the specification
//
// Children are generated by ladder.Generate, which returns them in A.7's rung
// order (RECON first), then STABLY reordered by an integer priority:
//
//	0  the action OVERLAPS a committed fault in time and names the SAME target.
//	   A.7 Rung 4 states this bias in normative text: "Bias toward overlapping
//	   proc.pause with net.partition — this is the canonical Raft lease bug
//	   trigger." Without it, strict rung order spends the entire budget on RECON
//	   and STRESS children before reaching a single PARTITION, and at ~62
//	   rollouts the compound interaction is simply never reached.
//	1  the action names the target the Tier 1 probe measured a REINFORCE signal
//	   on. A.5 roots Tier 2 at "the top-ranked REINFORCE signals", so the target
//	   that produced the signal is the prior; the CLASSIFICATION supplies it, and
//	   nothing here names a node, a role or a millisecond.
//	2  everything else, in pure ladder order.
//
// Priorities are integers and the sort is stable, so the order is a function of
// the ladder's own output and of the measured prior, never of map iteration,
// never of a float comparison a different architecture could fuse differently.
// ---------------------------------------------------------------------------

// ErrTree reports a tree that cannot be built or advanced.
var ErrTree = errors.New("saboteur: mcts tree")

// DefaultMaxDepth is A.5's "maximum tree depth: 4 additional faults beyond the
// triggering probe fault", matching schema.DefaultMaxMCTSDepth.
const DefaultMaxDepth = schema.DefaultMaxMCTSDepth

// DefaultEscalateAtMS is where the root action's window opens when the caller
// names no other offset.
//
// It is NOT D-031's 8200. The escalation's geometry is what reproduces the
// fixture anomaly (an outer fault that opens CompoundLeadInMS before the inner
// one and outlasts it by at least CompoundTailMinMS, with the pause strictly
// under the lease) and that geometry holds at any offset. Anchoring the default
// on D-031's measured millisecond would bake the answer into the search, which
// is exactly what A.9 #2's "no hardcoded fault schedules" forbids.
//
// 3000 ms is chosen so the window opens after the driver has ramped (SEED has
// already proved steady state) and closes early enough that a five-fault branch
// still fits inside a DRIVE phase, since PERTURB blocks until the last
// withdrawal and a world therefore costs what its schedule spans.
const DefaultEscalateAtMS int64 = 3000

// Node is one branch of the tree: a complete fault schedule and its evidence.
type Node struct {
	// Depth is the number of ladder actions applied below the root. The root is
	// depth 0 even when it carries committed faults.
	Depth int
	// Faults is the COMPLETE planned schedule at this node, canonical and
	// sorted. It is what a rollout executes.
	Faults []string
	// Action is the edge that produced this node. The root's is the zero value.
	Action Action
	// Parent is nil at the root.
	Parent *Node
	// Children is the expansion, in selection order. Nil until Expanded.
	Children []*Node
	// Expanded records that the ladder has been asked for this node's children.
	// A node with Expanded true and no children is TERMINAL: the depth cap, the
	// fault ceiling, or a ladder that could generate nothing legal here.
	Expanded bool

	// Pruned marks A.5's "proven uninteresting" rule. A pruned node is never
	// selected again; it is retained so Stats can report how often the rule
	// actually fired.
	Pruned   bool
	PruneWhy string

	// Pending marks a node that Select has handed out but whose rollout has not
	// yet been backpropagated.
	//
	// It is the whole of this tree's parallelisation story, and it is here
	// because the executor runs four worlds at once: without it, Select would
	// return the same unvisited node four times and the batch would execute one
	// schedule four times while reporting four rollouts. It is the standard
	// "virtual loss", implemented as exclusion rather than as a fabricated
	// negative utility: an invented loss would be backpropagated evidence
	// nobody measured.
	Pending bool

	// Visits and TotalUtility are the backpropagation accumulators.
	Visits       int
	TotalUtility float64
	// Rollouts counts executions that terminated AT this node, as opposed to
	// visits, which count paths through it.
	Rollouts int
	// NovelTotal and ViolationTotal are the pruning rule's two inputs: A.5
	// prunes on "zero coverage delta and zero violations".
	NovelTotal     int64
	ViolationTotal int
}

// AvgUtility is U_avg for this node.
func (n *Node) AvgUtility() float64 { return AverageUtility(n.TotalUtility, n.Visits) }

// FaultCount is the parsimony tie-break's input.
func (n *Node) FaultCount() int { return len(n.Faults) }

// Path renders the ladder actions from the root to this node.
func (n *Node) Path() []Action {
	var out []Action
	for cur := n; cur != nil && cur.Parent != nil; cur = cur.Parent {
		out = append(out, cur.Action)
	}
	// Reverse into root-first order.
	for i, j := 0, len(out)-1; i < j; i, j = i+1, j-1 {
		out[i], out[j] = out[j], out[i]
	}
	return out
}

// TreeOptions builds a tree.
type TreeOptions struct {
	// Config, Topology and Seed are the ladder's requirements and carry the
	// same meaning here.
	Config   *schema.Config
	Topology *perturber.Topology
	Seed     recorder.Seed

	// Root is the committed prefix: A.5's "active probe fault". It may be
	// empty, which roots the tree at the no-fault world.
	Root []string

	// AtMS is where a DEPTH-1 action's window opens. Deeper expansions derive
	// their own offset from the branch, so an added outer fault CONTAINS the
	// faults already committed (see expandAt).
	AtMS int64

	// MaxDepth is A.5's cap on additional faults. Zero means DefaultMaxDepth.
	MaxDepth int
	// MaxFaults is the hard per-world ceiling, from perturber.budget and the
	// search's own MaxFaultsPerWorld. Zero means no separate ceiling; the depth
	// cap still applies.
	MaxFaults int
	// Exploration is UCT's C. Zero means DefaultExploration. It cannot change a
	// decision at Addendum A's budgets; see uct.go.
	Exploration float64

	// PriorTarget is the target the Tier 1 probe measured its REINFORCE signal
	// on, or "". It only reorders children; it never adds or removes one.
	PriorTarget string

	// LeaseMS, Timing and KindSupported are handed to the ladder unchanged.
	LeaseMS       int64
	Timing        LadderTiming
	KindSupported func(schema.FaultKind) error
}

func (o *TreeOptions) fill() {
	if o.MaxDepth <= 0 {
		o.MaxDepth = DefaultMaxDepth
	}
	if o.Exploration == 0 {
		o.Exploration = DefaultExploration
	}
	if o.AtMS <= 0 {
		o.AtMS = DefaultEscalateAtMS
	}
	if o.LeaseMS == 0 {
		o.LeaseMS = DefaultLeaseMS
	}
	if o.Timing == (LadderTiming{}) {
		o.Timing = DefaultTiming()
	}
}

// Tree is the search tree over one root.
type Tree struct {
	opts TreeOptions
	root *Node

	nodes int
	// forced and informed count selections by kind. They are the measurement
	// D-015 asks for and are reported verbatim rather than interpreted.
	forced   int
	informed int
	// prunes counts nodes A.5's rule actually removed.
	prunes int
	// expansions counts ladder invocations, and skips the actions it refused.
	expansions int
	skips      []Skip
}

// NewTree builds the tree and its root. The root is NOT expanded until the
// first Select, so building a tree costs no ladder work.
func NewTree(opts TreeOptions) (*Tree, error) {
	if opts.Config == nil || opts.Topology == nil {
		return nil, fmt.Errorf("%w: needs a config and a topology", ErrTree)
	}
	opts.fill()
	root := &Node{Depth: 0, Faults: append([]string(nil), opts.Root...)}
	sort.Strings(root.Faults)
	return &Tree{opts: opts, root: root, nodes: 1}, nil
}

// Root returns the tree's root node.
func (t *Tree) Root() *Node { return t.root }

// Select descends to the node whose schedule should be executed next.
//
// It is the standard MCTS descent: from the root, expand where necessary and
// follow the best child until it reaches either a node that has never been
// visited (the rollout) or a terminal node with no legal children.
//
// It returns ErrExhaustedTree when every branch below the root has been pruned
// or executed and there is nothing left to try, which is a normal end to a
// search and not a failure.
func (t *Tree) Select() (*Node, error) {
	n := t.root
	for {
		if !n.Expanded {
			if err := t.expand(n); err != nil {
				return nil, err
			}
		}
		live := liveChildren(n)
		if len(live) == 0 {
			// Terminal. If it has already been executed or is in flight there
			// is nothing here to learn; walk back up looking for another branch.
			if n.Visits > 0 || n.Pending {
				alt := t.nextUnexecuted(t.root)
				if alt == nil {
					return nil, ErrExhaustedTree
				}
				alt.Pending = true
				return alt, nil
			}
			n.Pending = true
			return n, nil
		}
		best, kind := t.selectChild(n, live)
		switch kind {
		case SelectionForced:
			t.forced++
		case SelectionInformed:
			t.informed++
		}
		n = best
		if n.Visits == 0 {
			n.Pending = true
			return n, nil
		}
	}
}

// ErrExhaustedTree reports that the tree has no unexecuted branch left.
var ErrExhaustedTree = errors.New("saboteur: the tree has no unexecuted branch left")

// nextUnexecuted finds the first unvisited, unpruned node in expansion order.
// It is the fallback when a descent lands on an already-executed terminal, and
// it preserves the ladder's ordering because Children is already in that order.
func (t *Tree) nextUnexecuted(n *Node) *Node {
	if n.Pruned {
		return nil
	}
	if n.Visits == 0 && !n.Pending {
		return n
	}
	for _, c := range n.Children {
		if found := t.nextUnexecuted(c); found != nil {
			return found
		}
	}
	return nil
}

// selectChild applies the UCT policy over live children and reports whether the
// scores or the order decided.
func (t *Tree) selectChild(parent *Node, live []*Node) (*Node, SelectionKind) {
	if len(live) == 1 {
		if live[0].Visits == 0 {
			return live[0], SelectionForced
		}
		return live[0], SelectionNone
	}
	anyUnvisited := false
	for _, c := range live {
		if c.Visits == 0 {
			anyUnvisited = true
			break
		}
	}
	bestIdx := 0
	bestScore := UCT(live[0].AvgUtility(), live[0].Visits, parent.Visits, t.opts.Exploration)
	for i := 1; i < len(live); i++ {
		s := UCT(live[i].AvgUtility(), live[i].Visits, parent.Visits, t.opts.Exploration)
		if betterUCT(s, live[i].FaultCount(), i, bestScore, live[bestIdx].FaultCount(), bestIdx) {
			bestIdx, bestScore = i, s
		}
	}
	if anyUnvisited {
		return live[bestIdx], SelectionForced
	}
	return live[bestIdx], SelectionInformed
}

// liveChildren are the children still eligible for selection: neither pruned
// nor already handed out and awaiting a result.
func liveChildren(n *Node) []*Node {
	out := make([]*Node, 0, len(n.Children))
	for _, c := range n.Children {
		if c.Pruned {
			continue
		}
		if c.Pending && c.Visits == 0 {
			continue
		}
		out = append(out, c)
	}
	return out
}

// expand asks the ladder for this node's children.
//
// A node at the depth cap or the fault ceiling is expanded to NOTHING, and is
// marked expanded so it is never asked again. That is a terminal, not an error:
// A.5's tree is bounded on purpose because each rollout costs a real world.
func (t *Tree) expand(n *Node) error {
	n.Expanded = true
	if n.Depth >= t.opts.MaxDepth {
		return nil
	}
	if t.opts.MaxFaults > 0 && len(n.Faults) >= t.opts.MaxFaults {
		return nil
	}

	plan, err := Generate(LadderOptions{
		Config:        t.opts.Config,
		Topology:      t.opts.Topology,
		Seed:          t.opts.Seed,
		AtMS:          t.expandAt(n),
		Prefix:        n.Faults,
		KindSupported: t.opts.KindSupported,
		LeaseMS:       t.opts.LeaseMS,
		Timing:        t.opts.Timing,
	})
	if err != nil {
		return fmt.Errorf("%w: expand depth %d: %w", ErrTree, n.Depth, err)
	}
	t.expansions++
	t.skips = append(t.skips, plan.Skipped...)

	ordered := OrderActions(plan.Actions, n.Faults, t.opts.PriorTarget)
	for _, a := range ordered {
		faults := mergeFaults(n.Faults, a.Faults)
		if t.opts.MaxFaults > 0 && len(faults) > t.opts.MaxFaults {
			continue
		}
		child := &Node{
			Depth:  n.Depth + 1,
			Faults: faults,
			Action: a,
			Parent: n,
		}
		n.Children = append(n.Children, child)
		t.nodes++
	}
	return nil
}

// expandAt is where a new action's window opens for a given node.
//
// At depth 0 it is the caller's AtMS. Deeper, it is CompoundLeadInMS BEFORE the
// earliest committed fault, so an added durative fault opens before what is
// already there and (with the ladder's own tail rule) outlasts it. That is
// D-031's geometry expressed as arithmetic over the branch rather than as a
// constant: at AtMS 8300 with the default timing it yields exactly
// net.partition@8200..13500 around proc.pause@8300..11000, and it yields the
// same SHAPE at every other offset.
func (t *Tree) expandAt(n *Node) int64 {
	if len(n.Faults) == 0 {
		return t.opts.AtMS
	}
	earliest := int64(-1)
	for _, f := range n.Faults {
		spec, err := schema.ParseFault(f)
		if err != nil {
			continue
		}
		if earliest < 0 || spec.StartMS < earliest {
			earliest = spec.StartMS
		}
	}
	if earliest < 0 {
		return t.opts.AtMS
	}
	at := earliest - t.opts.Timing.CompoundLeadInMS
	if at < 0 {
		at = 0
	}
	return at
}

// mergeFaults joins a prefix with an action's faults, sorted and de-duplicated.
func mergeFaults(prefix, add []string) []string {
	seen := make(map[string]bool, len(prefix)+len(add))
	out := make([]string, 0, len(prefix)+len(add))
	for _, f := range prefix {
		if !seen[f] {
			seen[f] = true
			out = append(out, f)
		}
	}
	for _, f := range add {
		if !seen[f] {
			seen[f] = true
			out = append(out, f)
		}
	}
	sort.Strings(out)
	return out
}

// OrderActions applies the expansion order described at the top of this file.
//
// It is exported because it is the tree's actual prior and a test that could
// not reach it would be testing the arithmetic instead of the search.
func OrderActions(actions []Action, prefix []string, priorTarget string) []Action {
	type keyed struct {
		a   Action
		pri int
		idx int
	}
	prefixSpecs := make([]schema.FaultSpec, 0, len(prefix))
	for _, f := range prefix {
		if spec, err := schema.ParseFault(f); err == nil {
			prefixSpecs = append(prefixSpecs, spec)
		}
	}
	ks := make([]keyed, 0, len(actions))
	for i, a := range actions {
		ks = append(ks, keyed{a: a, pri: actionPriority(a, prefixSpecs, priorTarget), idx: i})
	}
	sort.SliceStable(ks, func(i, j int) bool {
		if ks[i].pri != ks[j].pri {
			return ks[i].pri < ks[j].pri
		}
		return ks[i].idx < ks[j].idx
	})
	out := make([]Action, 0, len(ks))
	for _, k := range ks {
		out = append(out, k.a)
	}
	return out
}

// Action priority tiers. Lower is tried first.
const (
	// PriorityOverlap is A.7 Rung 4's normative bias: an action that overlaps a
	// committed fault in time on the same target.
	PriorityOverlap = 0
	// PriorityPrior is the target the Tier 1 probe reinforced on.
	PriorityPrior = 1
	// PriorityLadder is pure A.7 rung order.
	PriorityLadder = 2
)

func actionPriority(a Action, prefix []schema.FaultSpec, priorTarget string) int {
	for _, f := range a.Faults {
		spec, err := schema.ParseFault(f)
		if err != nil {
			continue
		}
		for _, p := range prefix {
			if p.Target.String() != spec.Target.String() {
				continue
			}
			if overlaps(p, spec) {
				return PriorityOverlap
			}
		}
	}
	if priorTarget != "" && a.Target == priorTarget {
		return PriorityPrior
	}
	return PriorityLadder
}

// overlaps reports whether two fault windows intersect. Touching endpoints
// count: a fault withdrawn at exactly the millisecond another is injected is an
// interleaving the search is interested in, not a coincidence to discard.
func overlaps(a, b schema.FaultSpec) bool {
	return a.StartMS <= b.EndMS && b.StartMS <= a.EndMS
}

// RolloutResult is what one executed world tells the tree.
type RolloutResult struct {
	// Utility is A.6's payoff for the executed world.
	Utility float64
	// NewTemplates and NewStates are the coverage delta, which A.5's pruning
	// rule reads.
	NewTemplates int64
	NewStates    int64
	// Violations is the number of DEFINITE oracle violations. An inconclusive
	// oracle is not a violation and is not a clean result either; it simply
	// does not count here, and Evaluable carries that fact.
	Violations int
	// Evaluable reports whether the world produced a usable verdict at all. An
	// UNEVALUABLE world must not prune a node: "we could not tell" is not
	// "proven uninteresting", and treating it as such is the ranked #1 way this
	// phase fails.
	Evaluable bool
}

// Backpropagate folds one rollout's result up the path to the root.
//
// A.5: "compute utility U using the payoff function and propagate the value up
// to the root. Update U_avg and visits for each node on the path."
func (t *Tree) Backpropagate(n *Node, res RolloutResult) {
	if n == nil {
		return
	}
	n.Rollouts++
	n.Pending = false
	for cur := n; cur != nil; cur = cur.Parent {
		cur.Visits++
		cur.TotalUtility += res.Utility
		cur.NovelTotal += res.NewTemplates + res.NewStates
		cur.ViolationTotal += res.Violations
	}
	t.prune(n, res)
}

// prune applies A.5's rule: "if a node has been visited >= 3 times with zero
// coverage delta and zero violations, prune it from the tree (proven
// uninteresting)".
//
// Two guards the rule as written does not have, and both are load-bearing:
//
//   - the ROOT is never pruned, because pruning it would end the search while
//     claiming the branch was explored;
//   - an UNEVALUABLE rollout does not count toward "proven uninteresting". A
//     world whose oracles could not answer has established nothing, and letting
//     it prune a branch would let harness trouble quietly delete the part of the
//     space the search was about to reach.
func (t *Tree) prune(n *Node, res RolloutResult) {
	if !res.Evaluable {
		return
	}
	for cur := n; cur != nil && cur.Parent != nil; cur = cur.Parent {
		if cur.Pruned {
			continue
		}
		if cur.Visits >= PruneVisits && cur.NovelTotal == 0 && cur.ViolationTotal == 0 {
			cur.Pruned = true
			cur.PruneWhy = fmt.Sprintf("visited %d times with zero coverage delta and zero violations (A.5)",
				cur.Visits)
			t.prunes++
		}
	}
}

// TreeStats is what the tree measured about itself.
//
// It exists so the D-015 claim is reported as an observation rather than
// asserted as a belief: InformedSelections is the number of times a
// backpropagated utility could have changed which child was chosen.
type TreeStats struct {
	Nodes              int
	Expansions         int
	ForcedSelections   int
	InformedSelections int
	Pruned             int
	MaxVisits          int
	RevisitedNodes     int
	Skipped            []Skip
}

// TreeContributed reports whether backpropagation ever influenced a decision.
// False means the tree behaved exactly as ladder-ordered enumeration.
func (s TreeStats) TreeContributed() bool { return s.InformedSelections > 0 }

// Stats walks the tree and reports what actually happened in it.
func (t *Tree) Stats() TreeStats {
	s := TreeStats{
		Nodes:              t.nodes,
		Expansions:         t.expansions,
		ForcedSelections:   t.forced,
		InformedSelections: t.informed,
		Pruned:             t.prunes,
		Skipped:            t.skips,
	}
	var walk func(*Node)
	walk = func(n *Node) {
		if n.Visits > s.MaxVisits {
			s.MaxVisits = n.Visits
		}
		if n.Visits >= 2 {
			s.RevisitedNodes++
		}
		for _, c := range n.Children {
			walk(c)
		}
	}
	walk(t.root)
	return s
}

// Best returns the highest-utility executed node, with A.5's parsimony
// tie-break. It is what a search reports as its best finding.
func (t *Tree) Best() *Node {
	var best *Node
	var walk func(*Node)
	walk = func(n *Node) {
		if n.Visits > 0 && (best == nil || betterUCT(
			n.AvgUtility(), n.FaultCount(), 0,
			best.AvgUtility(), best.FaultCount(), 1)) {
			best = n
		}
		for _, c := range n.Children {
			walk(c)
		}
	}
	walk(t.root)
	return best
}
