package faults

import (
	"strings"
	"testing"
)

// A real capture, taken from an unmodified nginx:alpine container on this
// machine. The nat-table rules are the container's OWN (Docker's embedded DNS
// resolver installs them) and they are exactly why an assumed-empty residual
// check false-fails on an unmodified target (D-026).
const sampleCapture = `#ADDR
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
1: lo    inet6 ::1/128 scope host proto kernel_lo \       valid_lft forever preferred_lft forever
2: eth0    inet 172.23.0.2/16 brd 172.23.255.255 scope global eth0\       valid_lft forever preferred_lft forever
3: eth1    inet 172.30.0.4/24 brd 172.30.0.255 scope global eth1\       valid_lft forever preferred_lft forever
#QDISC
qdisc noqueue 0: dev lo root refcnt 2
qdisc noqueue 0: dev eth0 root refcnt 2
qdisc noqueue 0: dev eth1 root refcnt 2
#IPT4
# Generated by iptables-save v1.8.10 (nf_tables) on Mon Sep  7 09:17:15 2026
*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER_OUTPUT - [0:0]
-A OUTPUT -d 127.0.0.11/32 -j DOCKER_OUTPUT
-A DOCKER_OUTPUT -d 127.0.0.11/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.0.0.11:46367
COMMIT
# Completed on Mon Sep  7 09:17:15 2026
#IPT6
#END
`

func TestParseCapture(t *testing.T) {
	c, err := parseCapture(sampleCapture)
	if err != nil {
		t.Fatalf("parseCapture: %v", err)
	}
	if len(c.Ifaces) != 3 {
		t.Fatalf("got %d interfaces, want eth0, eth1, lo: %+v", len(c.Ifaces), c.Ifaces)
	}
	// Sorted by name, so the order is eth0, eth1, lo: stable regardless of the
	// order `ip -o addr show` happened to print them in.
	if c.Ifaces[0].Name != "eth0" || c.Ifaces[0].CIDRs[0] != "172.23.0.2/16" {
		t.Fatalf("eth0 parsed as %+v", c.Ifaces[0])
	}
	if c.Ifaces[1].Name != "eth1" || c.Ifaces[1].CIDRs[0] != "172.30.0.4/24" {
		t.Fatalf("eth1 parsed as %+v", c.Ifaces[1])
	}
	if c.Ifaces[2].Name != "lo" || len(c.Ifaces[2].CIDRs) != 2 {
		t.Fatalf("lo should carry both its v4 and v6 address: %+v", c.Ifaces[2])
	}
	if len(c.Qdiscs) != 3 {
		t.Fatalf("got %d qdiscs, want 3: %v", len(c.Qdiscs), c.Qdiscs)
	}
	for _, q := range c.Qdiscs {
		if strings.Contains(q, "refcnt") {
			t.Fatalf("qdisc line %q still carries refcnt, which varies with namespace references", q)
		}
	}
	if len(c.IP6Tables) != 0 {
		t.Fatalf("an empty ip6tables-save must parse as no rules, got %v", c.IP6Tables)
	}
}

// iptables-save stamps a wall clock on every dump and prints per-chain packet
// counters. Both change between any two dumps of an unchanged table, so a raw
// comparison would report every node dirty.
func TestCaptureNormalizationStripsTimestampsAndCounters(t *testing.T) {
	c, err := parseCapture(sampleCapture)
	if err != nil {
		t.Fatalf("parseCapture: %v", err)
	}
	for _, l := range c.IPTables {
		if strings.HasPrefix(l, "#") {
			t.Fatalf("dump comment %q survived normalization; it carries a timestamp", l)
		}
		if strings.HasPrefix(l, ":") && strings.HasSuffix(l, "]") {
			t.Fatalf("chain line %q still carries its packet counters", l)
		}
	}
	if want := ":PREROUTING ACCEPT"; !contains(c.IPTables, want) {
		t.Fatalf("normalized chain line %q missing from %v", want, c.IPTables)
	}
}

func TestParseCaptureRejectsTruncatedOutput(t *testing.T) {
	truncated := strings.TrimSuffix(sampleCapture, "#END\n")
	if _, err := parseCapture(truncated); err == nil {
		t.Fatal("a truncated snapshot must be an error; half a table read as a full one " +
			"would report residue that is not there, or miss residue that is")
	}
}

func TestParseCaptureRejectsUnmarkedOutput(t *testing.T) {
	if _, err := parseCapture("iptables: command not found\n"); err == nil {
		t.Fatal("output with no section markers must be an error, not an empty baseline")
	}
}

// This is the case D-026 was written about: the target ships its own rules, and
// an assumed-empty check reports a violation on a system nobody touched.
func TestBaselineDiffIgnoresTheTargetsOwnRules(t *testing.T) {
	c, err := parseCapture(sampleCapture)
	if err != nil {
		t.Fatalf("parseCapture: %v", err)
	}
	base := Baseline{NodeID: "n1", Qdiscs: c.Qdiscs, IPTables: c.IPTables, Ifaces: c.Ifaces}
	res := diffBaseline("n1", base, c)
	if !res.Clean() {
		t.Fatalf("an unchanged node reported residue: %+v", res)
	}
}

func TestBaselineDiffFindsTaggedRules(t *testing.T) {
	base := Baseline{NodeID: "n1"}
	cur := capture{IPTables: []string{
		"-A INPUT -s 172.23.0.3/32 -m comment --comment \"thesis:r1:f1\" -j DROP",
		"-A OUTPUT -d 127.0.0.11/32 -j DOCKER_OUTPUT",
	}}
	res := diffBaseline("n1", base, cur)
	if len(res.TaggedRules) != 1 {
		t.Fatalf("got %d tagged rules, want 1: %+v", len(res.TaggedRules), res)
	}
	if res.Clean() {
		t.Fatal("a surviving tagged rule is a leak and must fail HEAL")
	}
	if !strings.Contains(res.Summary(), "tagged iptables rule") {
		t.Fatalf("summary does not name the problem: %q", res.Summary())
	}
}

// tc carries no ownership tag, so a qdisc that was not there at BOOT is the
// only evidence of residual shaping there can be.
func TestBaselineDiffFindsResidualQdisc(t *testing.T) {
	base := Baseline{NodeID: "n1", Qdiscs: []string{"qdisc noqueue 0: dev eth0 root"}}
	cur := capture{Qdiscs: []string{
		"qdisc prio 1: dev eth0 root bands 16 priomap 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1",
		"qdisc netem 30: dev eth0 parent 1:3 limit 1000 delay 40ms seed 7",
	}}
	res := diffBaseline("n1", base, cur)
	if len(res.QdiscAdded) != 2 {
		t.Fatalf("got %d added qdiscs, want 2: %+v", len(res.QdiscAdded), res)
	}
	if len(res.QdiscRemoved) != 1 {
		t.Fatalf("the BOOT noqueue root is gone and that must be reported too: %+v", res)
	}
	if res.Clean() {
		t.Fatal("residual shaping must fail HEAL")
	}
}

// A target is entitled to change its own rules while a run is in progress.
// Reporting that as our leak is the false failure D-026 exists to prevent.
func TestUntaggedDriftIsInformationalOnly(t *testing.T) {
	base := Baseline{NodeID: "n1", IPTables: []string{"-A INPUT -p tcp --dport 80 -j ACCEPT"}}
	cur := capture{IPTables: []string{
		"-A INPUT -p tcp --dport 80 -j ACCEPT",
		"-A INPUT -p tcp --dport 443 -j ACCEPT",
	}}
	res := diffBaseline("n1", base, cur)
	if !res.Clean() {
		t.Fatalf("an untagged rule the target added is not our residue: %+v", res)
	}
	if len(res.RuleDrift) != 1 {
		t.Fatalf("drift should still be reported for diagnosis, got %v", res.RuleDrift)
	}
}

// Two identical DROP rules are two rules. A residual check that deduplicated
// would remove one and report clean.
func TestSubtractMultisetCountsDuplicates(t *testing.T) {
	got := subtractMultiset([]string{"a", "a", "b"}, []string{"a"})
	if len(got) != 2 || got[0] != "a" || got[1] != "b" {
		t.Fatalf("subtractMultiset = %v, want [a b]", got)
	}
}

func TestResidueNotRunningIsClean(t *testing.T) {
	r := Residue{NodeID: "n1", NotRunning: true}
	if !r.Clean() {
		t.Fatal("a container that is gone took its network namespace with it; that is clean")
	}
	if !strings.Contains(r.Summary(), "network namespace") {
		t.Fatalf("summary should say why it is clean: %q", r.Summary())
	}
}

// An unreachable node verified NOTHING. Reporting it clean would be the vacuous
// pass this whole design exists to avoid.
func TestResidueUnreachableIsNotClean(t *testing.T) {
	r := Residue{NodeID: "n1", Unreachable: "daemon refused"}
	if r.Clean() {
		t.Fatal("a node that could not be inspected must not count as verified clean")
	}
}

func TestResidualReportErr(t *testing.T) {
	clean := &ResidualReport{Nodes: []Residue{{NodeID: "n1"}}}
	if err := clean.Err(); err != nil {
		t.Fatalf("clean report returned %v", err)
	}
	dirty := &ResidualReport{Nodes: []Residue{{NodeID: "n1", TaggedRules: []string{"x"}}}}
	if dirty.Err() == nil {
		t.Fatal("a report with residue must produce an error")
	}
	stray := &ResidualReport{Nodes: []Residue{{NodeID: "n1"}}, StraySidecars: 1}
	if stray.Err() == nil {
		t.Fatal("a leaked sidecar holds the target's netns open and must fail HEAL")
	}
	var nilReport *ResidualReport
	if nilReport.Err() == nil {
		t.Fatal("a report that never ran must not read as clean")
	}
}

func TestBaselineSetRoundTrip(t *testing.T) {
	c, err := parseCapture(sampleCapture)
	if err != nil {
		t.Fatalf("parseCapture: %v", err)
	}
	set := &BaselineSet{
		Schema: BaselineSchema,
		RunID:  "r_2026_09_07_a41f",
		Nodes: []Baseline{{
			NodeID: "kv-n1", ContainerID: "abc123",
			Ifaces: c.Ifaces, Qdiscs: c.Qdiscs, IPTables: c.IPTables, IP6Tables: c.IP6Tables,
		}},
	}
	data, err := set.Encode()
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	back, err := DecodeBaselines(data)
	if err != nil {
		t.Fatalf("DecodeBaselines: %v", err)
	}
	again, err := back.Encode()
	if err != nil {
		t.Fatalf("re-Encode: %v", err)
	}
	if string(data) != string(again) {
		t.Fatal("the baseline artifact is not byte-stable across a round trip, " +
			"so the run bundle's MANIFEST hash would move on its own")
	}
	if _, ok := back.Node("kv-n1"); !ok {
		t.Fatal("node lookup failed after a round trip")
	}
}

func TestDecodeBaselinesRejectsWrongSchema(t *testing.T) {
	if _, err := DecodeBaselines([]byte(`{"schema":"other/v1","run_id":"r","nodes":[]}`)); err == nil {
		t.Fatal("a baseline with an unknown schema must not be read as this one")
	}
}

func contains(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
