package faults

import (
	"context"
	"fmt"
	"strings"
	"sync"
)

// fakeRunner stands in for the Docker CLI so the whole injector (planning,
// slot allocation, rollback, withdrawal self-check) is testable without a
// daemon. The integration test exercises the real thing separately.
type fakeRunner struct {
	mu      sync.Mutex
	calls   []fakeCall
	respond func(c fakeCall) (string, string, error)
}

type fakeCall struct {
	Name string
	Args []string
	// Script is the `-c` argument of a `docker run`, when there is one.
	Script string
	// Target is the container named by `--network container:<id>`.
	Target string
	// Sub is the docker subcommand: run, inspect, ps, rm, image, build.
	Sub string
}

func (f *fakeRunner) Run(_ context.Context, _ []byte, name string, args ...string) (string, string, error) {
	c := fakeCall{Name: name, Args: append([]string(nil), args...)}
	if len(args) > 0 {
		c.Sub = args[0]
	}
	for i, a := range args {
		if a == "-c" && i+1 < len(args) {
			c.Script = args[i+1]
		}
		if a == "--network" && i+1 < len(args) {
			c.Target = strings.TrimPrefix(args[i+1], "container:")
		}
	}
	f.mu.Lock()
	f.calls = append(f.calls, c)
	respond := f.respond
	f.mu.Unlock()
	if respond == nil {
		return "", "", nil
	}
	return respond(c)
}

func (f *fakeRunner) scripts() []string {
	f.mu.Lock()
	defer f.mu.Unlock()
	var out []string
	for _, c := range f.calls {
		if c.Script != "" {
			out = append(out, c.Script)
		}
	}
	return out
}

func (f *fakeRunner) subcommands(sub string) []fakeCall {
	f.mu.Lock()
	defer f.mu.Unlock()
	var out []fakeCall
	for _, c := range f.calls {
		if c.Sub == sub {
			out = append(out, c)
		}
	}
	return out
}

// fakeWorld drives the runner with a small model of three containers on two
// networks, matching the reference fixture's client/peer split.
type fakeWorld struct {
	// capture is what a snapshot sidecar returns per container. It starts as
	// the clean sample and tests mutate it to simulate residue.
	capture map[string]string
	// running reports container liveness.
	running map[string]bool
	// injectFails makes the injection script fail on a given container.
	injectFails map[string]bool
	// taggedAfterWithdraw is what the withdrawal self-check reports.
	taggedAfterWithdraw int
	// qdiscAfterWithdraw is what the withdrawal self-check reports for tc.
	qdiscAfterWithdraw []string
}

const fakeAddrsJSON = `{"State":{"Running":true},"NetworkSettings":{"Networks":` +
	`{"kvclient":{"IPAddress":"172.23.0.%d","GlobalIPv6Address":""},` +
	`"kvpeer":{"IPAddress":"172.30.0.%d","GlobalIPv6Address":""}}}}`

func newFakeWorld() *fakeWorld {
	w := &fakeWorld{
		capture:     map[string]string{},
		running:     map[string]bool{},
		injectFails: map[string]bool{},
	}
	for i := 1; i <= 3; i++ {
		cid := fmt.Sprintf("c-kv-n%d", i)
		w.capture[cid] = fakeCaptureFor(i)
		w.running[cid] = true
	}
	return w
}

// fakeCaptureFor builds a per-node snapshot with the two-plane addressing the
// reference fixture uses: a published client network and an internal peer
// network.
func fakeCaptureFor(i int) string {
	return fmt.Sprintf(`#ADDR
1: lo    inet 127.0.0.1/8 scope host lo
2: eth0    inet 172.23.0.%d/16 brd 172.23.255.255 scope global eth0
3: eth1    inet 172.30.0.%d/24 brd 172.30.0.255 scope global eth1
#QDISC
qdisc noqueue 0: dev lo root refcnt 2
qdisc noqueue 0: dev eth0 root refcnt 2
qdisc noqueue 0: dev eth1 root refcnt 2
#IPT4
# Generated by iptables-save v1.8.10 (nf_tables) on Mon Sep  7 09:17:15 2026
*filter
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Mon Sep  7 09:17:15 2026
#IPT6
#END
`, i+1, i+1)
}

func (w *fakeWorld) respond(c fakeCall) (string, string, error) {
	switch {
	case c.Sub == "image":
		return "sha256:deadbeef\n", "", nil

	case c.Sub == "inspect":
		var b strings.Builder
		for _, a := range c.Args[2:] { // skip "inspect" "--format" "{{json .}}"
			if a == "{{json .}}" || a == "--format" {
				continue
			}
			n := 0
			fmt.Sscanf(a, "c-kv-n%d", &n)
			doc := fmt.Sprintf(fakeAddrsJSON, n+1, n+1)
			if !w.running[a] {
				doc = strings.Replace(doc, `"Running":true`, `"Running":false`, 1)
			}
			b.WriteString(doc)
			b.WriteByte('\n')
		}
		return b.String(), "", nil

	case c.Sub == "ps":
		return "", "", nil

	case c.Sub == "rm":
		return "", "", nil

	case c.Sub == "run":
		if !w.running[c.Target] {
			return "", "cannot join network of a non running container", fmt.Errorf("exit status 125")
		}
		switch {
		case strings.Contains(c.Script, "#ADDR"):
			return w.capture[c.Target], "", nil
		case strings.Contains(c.Script, "#TAGGED"):
			var b strings.Builder
			b.WriteString("#TAGGED\n")
			fmt.Fprintf(&b, "%d\n", w.taggedAfterWithdraw)
			b.WriteString("#QDISC\n")
			for _, q := range w.qdiscAfterWithdraw {
				b.WriteString(q + "\n")
			}
			b.WriteString("#END\n")
			return b.String(), "", nil
		default:
			if w.injectFails[c.Target] {
				return "", "iptables: Permission denied", fmt.Errorf("exit status 1")
			}
			return "", "", nil
		}
	}
	return "", "", nil
}

func newFakeInjector(w *fakeWorld) (*Injector, *fakeRunner, error) {
	r := &fakeRunner{respond: w.respond}
	nodes := []NetNode{
		{NodeID: "kv-n1", ContainerID: "c-kv-n1", ComposeService: "kv-n1", Group: "kv"},
		{NodeID: "kv-n2", ContainerID: "c-kv-n2", ComposeService: "kv-n2", Group: "kv"},
		{NodeID: "kv-n3", ContainerID: "c-kv-n3", ComposeService: "kv-n3", Group: "kv"},
	}
	tick := int64(1_000_000_000)
	in, err := NewInjector(Options{
		RunID:     "r_2026_09_07_a41f",
		WorldSeed: 20260906,
		Nodes:     nodes,
		Runner:    r,
		Now: func() int64 {
			tick += 1_000_000
			return tick
		},
	})
	return in, r, err
}
